version: "3.1"

services:
  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  api:
    build: .
    image: thinkful-ed/zid-be-creating-relations-03-joining-tables
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432
      NODE_ENV: test
